### ISSUE TITLE
What happens is the user id becomes public? 

### ISSUE THREAD

**Issue by tmdew** [nxvvvv/warp-plus#16]
What is the purpose of user id in the warp app for android? what happens if it become public? Someone else could use it to access the same Gateway features as you, such as HTTP filtering, browser isolation, and identity-based policies? Any risk involved?

**Comment by nxvvvv** [comment]
There ain't any problem that I know of. You can just Clear Data and get a new ID and yea. Key becoming public can be a nuisance since people can use that key for themselves and sometimes you'll get logged out and yea that key is gone💀. So yea
